/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bagus Perdana
 */
public class framekalkulator extends javax.swing.JFrame {
    
    String angka = "";
    double hasilhitung, angka1, angka2;
    int pilihoperator;
    /**
     * Creates new form framekalkulator
     */
    public framekalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kalkulatorjdl = new javax.swing.JLabel();
        txttampil = new javax.swing.JTextField();
        tmbltujuh = new javax.swing.JButton();
        tmbldelapan = new javax.swing.JButton();
        tmblsembilan = new javax.swing.JButton();
        tmblempat = new javax.swing.JButton();
        tmbllima = new javax.swing.JButton();
        tmblenam = new javax.swing.JButton();
        tmblsatu = new javax.swing.JButton();
        tmbldua = new javax.swing.JButton();
        tmbltiga = new javax.swing.JButton();
        tmblbersih = new javax.swing.JButton();
        tmblnol = new javax.swing.JButton();
        tmblkoma = new javax.swing.JButton();
        tmbltambah = new javax.swing.JButton();
        tmblkurang = new javax.swing.JButton();
        tmblbagi = new javax.swing.JButton();
        tmblkali = new javax.swing.JButton();
        tmblsamadengan = new javax.swing.JButton();
        nmpembuat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Manual (Bagus)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        kalkulatorjdl.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        kalkulatorjdl.setText("Kalkulator");

        txttampil.setEditable(false);
        txttampil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttampilActionPerformed(evt);
            }
        });

        tmbltujuh.setBackground(new java.awt.Color(0, 0, 0));
        tmbltujuh.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmbltujuh.setForeground(new java.awt.Color(255, 255, 255));
        tmbltujuh.setText("7");
        tmbltujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbltujuhActionPerformed(evt);
            }
        });

        tmbldelapan.setBackground(new java.awt.Color(0, 0, 0));
        tmbldelapan.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmbldelapan.setForeground(new java.awt.Color(255, 255, 255));
        tmbldelapan.setText("8");
        tmbldelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbldelapanActionPerformed(evt);
            }
        });

        tmblsembilan.setBackground(new java.awt.Color(0, 0, 0));
        tmblsembilan.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblsembilan.setForeground(new java.awt.Color(255, 255, 255));
        tmblsembilan.setText("9");
        tmblsembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblsembilanActionPerformed(evt);
            }
        });

        tmblempat.setBackground(new java.awt.Color(0, 0, 0));
        tmblempat.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblempat.setForeground(new java.awt.Color(255, 255, 255));
        tmblempat.setText("4");
        tmblempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblempatActionPerformed(evt);
            }
        });

        tmbllima.setBackground(new java.awt.Color(0, 0, 0));
        tmbllima.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmbllima.setForeground(new java.awt.Color(255, 255, 255));
        tmbllima.setText("5");
        tmbllima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbllimaActionPerformed(evt);
            }
        });

        tmblenam.setBackground(new java.awt.Color(0, 0, 0));
        tmblenam.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblenam.setForeground(new java.awt.Color(255, 255, 255));
        tmblenam.setText("6");
        tmblenam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblenamActionPerformed(evt);
            }
        });

        tmblsatu.setBackground(new java.awt.Color(0, 0, 0));
        tmblsatu.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblsatu.setForeground(new java.awt.Color(255, 255, 255));
        tmblsatu.setText("1");
        tmblsatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblsatuActionPerformed(evt);
            }
        });

        tmbldua.setBackground(new java.awt.Color(0, 0, 0));
        tmbldua.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmbldua.setForeground(new java.awt.Color(255, 255, 255));
        tmbldua.setText("2");
        tmbldua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblduaActionPerformed(evt);
            }
        });

        tmbltiga.setBackground(new java.awt.Color(0, 0, 0));
        tmbltiga.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmbltiga.setForeground(new java.awt.Color(255, 255, 255));
        tmbltiga.setText("3");
        tmbltiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbltigaActionPerformed(evt);
            }
        });

        tmblbersih.setBackground(new java.awt.Color(204, 0, 0));
        tmblbersih.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblbersih.setForeground(new java.awt.Color(255, 255, 255));
        tmblbersih.setText("C");
        tmblbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblbersihActionPerformed(evt);
            }
        });

        tmblnol.setBackground(new java.awt.Color(0, 0, 0));
        tmblnol.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblnol.setForeground(new java.awt.Color(255, 255, 255));
        tmblnol.setText("0");
        tmblnol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblnolActionPerformed(evt);
            }
        });

        tmblkoma.setBackground(new java.awt.Color(0, 0, 0));
        tmblkoma.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblkoma.setForeground(new java.awt.Color(255, 255, 255));
        tmblkoma.setText(".");
        tmblkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblkomaActionPerformed(evt);
            }
        });

        tmbltambah.setBackground(new java.awt.Color(0, 0, 0));
        tmbltambah.setForeground(new java.awt.Color(255, 255, 255));
        tmbltambah.setText("+");
        tmbltambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbltambahActionPerformed(evt);
            }
        });

        tmblkurang.setBackground(new java.awt.Color(0, 0, 0));
        tmblkurang.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblkurang.setForeground(new java.awt.Color(255, 255, 255));
        tmblkurang.setText("-");
        tmblkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblkurangActionPerformed(evt);
            }
        });

        tmblbagi.setBackground(new java.awt.Color(0, 0, 0));
        tmblbagi.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblbagi.setForeground(new java.awt.Color(255, 255, 255));
        tmblbagi.setText("/");
        tmblbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblbagiActionPerformed(evt);
            }
        });

        tmblkali.setBackground(new java.awt.Color(0, 0, 0));
        tmblkali.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblkali.setForeground(new java.awt.Color(255, 255, 255));
        tmblkali.setText("x");
        tmblkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblkaliActionPerformed(evt);
            }
        });

        tmblsamadengan.setBackground(new java.awt.Color(51, 204, 255));
        tmblsamadengan.setFont(new java.awt.Font("Bodoni MT Black", 0, 16)); // NOI18N
        tmblsamadengan.setForeground(new java.awt.Color(255, 255, 255));
        tmblsamadengan.setText("=");
        tmblsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblsamadenganActionPerformed(evt);
            }
        });

        nmpembuat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nmpembuat.setText("Dibuat Oleh : Bagus Perdana Yusuf");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(kalkulatorjdl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tmblbersih, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tmblnol, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tmblkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tmbltujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tmbldelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tmblsembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tmblempat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tmbllima, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tmblenam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tmblkali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tmblbagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tmbltambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tmblsatu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tmbldua, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tmbltiga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tmblkurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tmblsamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txttampil, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nmpembuat)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tmblbersih, tmbldelapan, tmbldua, tmblempat, tmblenam, tmbllima, tmblsatu, tmblsembilan, tmbltiga, tmbltujuh});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kalkulatorjdl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttampil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tmblbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tmbltujuh)
                        .addComponent(tmbldelapan)
                        .addComponent(tmblsembilan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tmblkali, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tmblempat)
                            .addComponent(tmbllima)
                            .addComponent(tmblenam))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tmblsatu)
                            .addComponent(tmbldua)
                            .addComponent(tmbltiga)
                            .addComponent(tmblkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tmblbersih)
                            .addComponent(tmblnol)
                            .addComponent(tmblkoma)
                            .addComponent(tmbltambah))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmblsamadengan)
                .addGap(18, 18, 18)
                .addComponent(nmpembuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tmblbagi, tmblbersih, tmbldelapan, tmbldua, tmblempat, tmblenam, tmblkali, tmblkoma, tmblkurang, tmbllima, tmblnol, tmblsatu, tmblsembilan, tmbltambah, tmbltiga, tmbltujuh});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttampilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttampilActionPerformed

    private void tmblnolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblnolActionPerformed
        // TODO add your handling code here:
        angka += "0";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmblnolActionPerformed

    private void tmblsatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblsatuActionPerformed
        // TODO add your handling code here:
        angka +="1";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmblsatuActionPerformed

    private void tmblduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblduaActionPerformed
        // TODO add your handling code here:
        angka +="2";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmblduaActionPerformed

    private void tmbltigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbltigaActionPerformed
        // TODO add your handling code here:
        angka +="3";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmbltigaActionPerformed

    private void tmblempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblempatActionPerformed
        // TODO add your handling code here:
        angka +="4";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmblempatActionPerformed

    private void tmbllimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbllimaActionPerformed
        // TODO add your handling code here:
        angka +="5";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmbllimaActionPerformed

    private void tmblenamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblenamActionPerformed
        // TODO add your handling code here:
        angka +="6";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmblenamActionPerformed

    private void tmbltujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbltujuhActionPerformed
        // TODO add your handling code here:
        angka +="7";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmbltujuhActionPerformed

    private void tmbldelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbldelapanActionPerformed
        // TODO add your handling code here:
        angka +="8";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmbldelapanActionPerformed

    private void tmblsembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblsembilanActionPerformed
        // TODO add your handling code here:
        angka +="9";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmblsembilanActionPerformed

    private void tmblbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblbersihActionPerformed
        // TODO add your handling code here:
        //fungsi untuk membersihkan pada tombol C
        txttampil.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        hasilhitung = 0.0;
        angka = "";
    }//GEN-LAST:event_tmblbersihActionPerformed

    private void tmblkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblkomaActionPerformed
        // TODO add your handling code here:
        angka +=".";
        txttampil.setText(angka);
    }//GEN-LAST:event_tmblkomaActionPerformed

    private void tmbltambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbltambahActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        txttampil.setText("+");
        angka="";
        pilihoperator = 1;
    }//GEN-LAST:event_tmbltambahActionPerformed

    private void tmblkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblkurangActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        txttampil.setText("-");
        angka="";
        pilihoperator = 2;
    }//GEN-LAST:event_tmblkurangActionPerformed

    private void tmblkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblkaliActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        txttampil.setText("*");
        angka="";
        pilihoperator = 3;
    }//GEN-LAST:event_tmblkaliActionPerformed

    private void tmblbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblbagiActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        txttampil.setText("/");
        angka="";
        pilihoperator = 4;
    }//GEN-LAST:event_tmblbagiActionPerformed

    private void tmblsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblsamadenganActionPerformed
        // TODO add your handling code here:
        switch (pilihoperator) {
            case 1 :
                angka2 = Double.parseDouble(angka);
                hasilhitung = angka1 + angka2;
                angka = Double.toString(hasilhitung);
                txttampil.setText(angka);
                break;
            case 2 :
                angka2 = Double.parseDouble(angka);
                hasilhitung = angka1 - angka2;
                angka = Double.toString(hasilhitung);
                txttampil.setText(angka);
                break;
            case 3 :
                angka2 = Double.parseDouble(angka);
                hasilhitung = angka1 * angka2;
                angka = Double.toString(hasilhitung);
                txttampil.setText(angka);
                break;
            case 4 :
                angka2 = Double.parseDouble(angka);
                hasilhitung = angka1 / angka2;
                angka = Double.toString(hasilhitung);
                txttampil.setText(angka);
                break;
                default:
                break;
        }
    }//GEN-LAST:event_tmblsamadenganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framekalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framekalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framekalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framekalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framekalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel kalkulatorjdl;
    private javax.swing.JLabel nmpembuat;
    private javax.swing.JButton tmblbagi;
    private javax.swing.JButton tmblbersih;
    private javax.swing.JButton tmbldelapan;
    private javax.swing.JButton tmbldua;
    private javax.swing.JButton tmblempat;
    private javax.swing.JButton tmblenam;
    private javax.swing.JButton tmblkali;
    private javax.swing.JButton tmblkoma;
    private javax.swing.JButton tmblkurang;
    private javax.swing.JButton tmbllima;
    private javax.swing.JButton tmblnol;
    private javax.swing.JButton tmblsamadengan;
    private javax.swing.JButton tmblsatu;
    private javax.swing.JButton tmblsembilan;
    private javax.swing.JButton tmbltambah;
    private javax.swing.JButton tmbltiga;
    private javax.swing.JButton tmbltujuh;
    private javax.swing.JTextField txttampil;
    // End of variables declaration//GEN-END:variables
}